import { Nunito_Sans } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import { useContext, useEffect, useState } from 'react';
import Layout from '../../components/Layout';
import Navbar from '../../components/Navbar';
import { UserContext } from '../../context/UserContext';
import { client } from '../../utils/appwriteConfig';
import withAuth from '../../utils/withAuth';

const nunito = Nunito_Sans({ subsets: ['latin'] });

function Home() {
  const { currentUser, loading } = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={nunito.className}>
          <Navbar />
          <div>{currentUser?.name}</div>
        </main>
      </Layout>
    </>
  );
}

export default withAuth(Home);
